import type { Metadata } from "next";
import { DM_Mono, DM_Sans } from "next/font/google";
import "./globals.sass";

const DMMono = DM_Mono({
  variable: "--font-dm-mono",
  subsets: ["latin-ext"],
  weight: "500",
  display: "swap",
});

const DMSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin-ext"],
  weight: "500",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${DMMono.variable} ${DMSans.variable}`}>
      <body>{children}</body>
    </html>
  );
}
